package com.saproduction.command.communication;
import com.saproduction.command.audit.AuditService;
import com.saproduction.command.meeting.MeetingService;
import com.saproduction.command.production.*;
import com.saproduction.command.shared.ApiException;
import java.time.Instant;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class InboundMessagingService {
  private final OutboundMessageRepository messages;private final OutboundMessageEventRepository history;private final ProductionService productions;private final MeetingService meetings;private final JdbcTemplate jdbc;private final AuditService audit;
  public InboundMessagingService(OutboundMessageRepository messages,OutboundMessageEventRepository history,ProductionService productions,MeetingService meetings,JdbcTemplate jdbc,AuditService audit){this.messages=messages;this.history=history;this.productions=productions;this.meetings=meetings;this.jdbc=jdbc;this.audit=audit;}
  @Transactional public boolean providerStatus(String receiptId,String providerMessageId,String status,String error){if(!receipt(receiptId,"STATUS"))return false;OutboundMessage message=messages.findByProviderMessageId(providerMessageId).orElseThrow(()->ApiException.notFound("MESSAGE_NOT_FOUND","Provider message was not found."));applyStatus(message,status,error);completeReceipt(receiptId);return true;}
  @Transactional public boolean providerResponse(String receiptId,String providerMessageId,String action){if(!receipt(receiptId,"INTERACTION"))return false;OutboundMessage message=messages.findByProviderMessageId(providerMessageId).orElseThrow(()->ApiException.notFound("MESSAGE_NOT_FOUND","Provider message was not found."));applyResponse(message,action);completeReceipt(receiptId);return true;}
  @Transactional public void simulateStatus(UUID messageId,String status,String error){OutboundMessage message=messages.findById(messageId).orElseThrow(()->ApiException.notFound("MESSAGE_NOT_FOUND","Message was not found."));applyStatus(message,status,error);}
  @Transactional public void simulateResponse(UUID messageId,String action){OutboundMessage message=messages.findById(messageId).orElseThrow(()->ApiException.notFound("MESSAGE_NOT_FOUND","Message was not found."));applyResponse(message,action);}
  private void applyStatus(OutboundMessage m,String raw,String error){String status=raw.toUpperCase(Locale.ROOT);Instant now=Instant.now();switch(status){case "SENT"->{if(m.status==OutboundMessage.Status.READ||m.status==OutboundMessage.Status.DELIVERED)return;m.status=OutboundMessage.Status.SENT;if(m.sentAt==null)m.sentAt=now;}case "DELIVERED"->{if(m.status==OutboundMessage.Status.READ)return;m.status=OutboundMessage.Status.DELIVERED;if(m.sentAt==null)m.sentAt=now;if(m.deliveredAt==null)m.deliveredAt=now;}case "READ"->{m.status=OutboundMessage.Status.READ;if(m.sentAt==null)m.sentAt=now;if(m.deliveredAt==null)m.deliveredAt=now;if(m.readAt==null)m.readAt=now;}case "FAILED"->{if(m.status==OutboundMessage.Status.READ)return;m.status=OutboundMessage.Status.FAILED;m.failedAt=now;m.lastError=clean(error,"Provider reported a delivery failure.");}default->throw ApiException.badRequest("UNSUPPORTED_MESSAGE_STATUS","Message status is not supported.");}messages.save(m);record(m,status,error);}
  private void applyResponse(OutboundMessage m,String raw){if(!m.requiresResponse)throw ApiException.conflict("MESSAGE_RESPONSE_NOT_EXPECTED","This message does not expect a response.");String action=raw.toUpperCase(Locale.ROOT);if(m.response!=null){if(m.response.equals(action))return;throw ApiException.conflict("MESSAGE_ALREADY_RESPONDED","This message already has a response.");}if("PRODUCTION".equals(m.relatedType)){ProductionMember.Status target=switch(action){case "CONFIRM","CONFIRMED"->ProductionMember.Status.CONFIRMED;case "DECLINE","DECLINED"->ProductionMember.Status.DECLINED;default->throw ApiException.badRequest("UNSUPPORTED_RESPONSE","Production response is not supported.");};productions.updateMemberStatus(m.relatedId,m.employeeId,new ProductionService.MemberStatusInput(target));m.response=target.name();}else if("MEETING".equals(m.relatedType)){MeetingService.Response target=switch(action){case "ACCEPT","ACCEPTED","ATTENDING"->MeetingService.Response.ACCEPTED;case "DECLINE","DECLINED"->MeetingService.Response.DECLINED;default->throw ApiException.badRequest("UNSUPPORTED_RESPONSE","Meeting response is not supported.");};meetings.updateAttendeeResponse(m.relatedId,m.employeeId,new MeetingService.ResponseInput(target));m.response=target.name();}else throw ApiException.badRequest("UNSUPPORTED_RESPONSE_TARGET","Message response target is not supported.");messages.save(m);record(m,"RESPONSE",m.response);audit.record("COMMUNICATION","EMPLOYEE_RESPONSE_PROCESSED",m.id.toString(),null,Map.of("response",m.response,"relatedType",m.relatedType,"relatedId",m.relatedId));}
  private boolean receipt(String id,String type){return jdbc.update("insert into webhook_receipts(provider_event_id,event_type) values (?,?) on conflict(provider_event_id) do nothing",id,type)==1;}
  private void completeReceipt(String id){jdbc.update("update webhook_receipts set processed_at=now() where provider_event_id=?",id);}
  private void record(OutboundMessage message,String type,String detail){OutboundMessageEvent e=new OutboundMessageEvent();e.outboundMessageId=message.id;e.eventType=type;e.detail=detail;history.save(e);}
  private static String clean(String value,String fallback){if(value==null||value.isBlank())return fallback;return value.substring(0,Math.min(1000,value.length()));}
}
