import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Beaker,RefreshCw,ShieldCheck,Wifi,Zap} from 'lucide-react';
import {WorkspaceHeader} from '../../components/layout/AppShell';
import {EmptyState,SAButton,SABentoCard,SkeletonCard,StatusBadge} from '../../components/ui/sa';
import {ThemeSwitch} from '../../components/layout/ThemeSwitch';
import {api,json} from '../../lib/api';
import type {CommunicationCentre,NotificationRule,OutboundMessage} from '../../types/domain';
export function SettingsPage(){return <><WorkspaceHeader title="Settings" subtitle="Appearance, notification automation and development tools."/><div className="settings-stack"><SABentoCard><ThemeSwitch/></SABentoCard><SABentoCard><div className="settings-row"><span><Wifi size={17}/><div><strong>Local API</strong><small>Spring Boot · configured desktop origin</small></div></span><StatusBadge tone="success">Connected when signed in</StatusBadge></div></SABentoCard><SABentoCard><div className="settings-row"><span><ShieldCheck size={17}/><div><strong>Session protection</strong><small>HttpOnly server-side session; no credential in localStorage</small></div></span><StatusBadge tone="success">Enabled</StatusBadge></div></SABentoCard><NotificationRules/><Simulator/></div></>}
function NotificationRules(){const client=useQueryClient(),rules=useQuery({queryKey:['notification-rules'],queryFn:()=>api<NotificationRule[]>('/notification-rules')});const update=useMutation({mutationFn:({rule,enabled,delayMinutes}:{rule:NotificationRule;enabled:boolean;delayMinutes:number})=>api<NotificationRule>(`/notification-rules/${rule.id}`,{method:'PATCH',...json({enabled,delayMinutes})}),onSuccess:()=>client.invalidateQueries({queryKey:['notification-rules']})});return <SABentoCard><div className="settings-section-title"><span><Zap size={17}/><div><strong>Notification automation</strong><small>Rules are evaluated before any outbound message is created.</small></div></span></div>{rules.isPending?<SkeletonCard/>:rules.isError?<EmptyState title="Rules unavailable" description="Notification policy could not be loaded."/>:<div className="automation-list">{rules.data?.map(rule=><div key={rule.id}><div><strong>{label(rule.eventType)}</strong><small>{rule.templateKey} · WhatsApp</small></div><label className="delay-field">Delay<input type="number" min="0" defaultValue={rule.delayMinutes} onBlur={e=>update.mutate({rule,enabled:rule.enabled,delayMinutes:Number(e.target.value)})}/><span>min</span></label><button className={`rule-switch ${rule.enabled?'on':''}`} role="switch" aria-checked={rule.enabled} onClick={()=>update.mutate({rule,enabled:!rule.enabled,delayMinutes:rule.delayMinutes})}><span/></button></div>)}</div>}</SABentoCard>}
function Simulator(){const client=useQueryClient(),messages=useQuery({queryKey:['demo','messages'],queryFn:()=>api<CommunicationCentre>('/demo/messages'),retry:false});const action=useMutation({mutationFn:({id,path}:{id:string;path:string})=>api<OutboundMessage>(`/demo/messages/${id}/${path}`,{method:'POST'}),onSuccess:()=>{client.invalidateQueries({queryKey:['demo','messages']});client.invalidateQueries({queryKey:['communications']});client.invalidateQueries({queryKey:['dashboard']})}});if(messages.isError)return null;return <SABentoCard><div className="settings-section-title"><span><Beaker size={17}/><div><strong>Messaging simulator</strong><small>Demo only · uses the same inbound service as Meta callbacks.</small></div></span><SAButton size="sm" onClick={()=>messages.refetch()}><RefreshCw size={13}/>Refresh</SAButton></div>{messages.isPending?<SkeletonCard/>:<div className="simulator-list">{messages.data?.messages.slice(0,6).map(m=><div key={m.id}><div><strong>{m.employeeName}</strong><small>{m.bodyPreview}</small></div><div>{(['SENT','DELIVERED','READ','FAILED'] as const).map(s=><button key={s} onClick={()=>action.mutate({id:m.id,path:s})}>{s}</button>)}{m.requiresResponse&&<><button onClick={()=>action.mutate({id:m.id,path:'respond/CONFIRM'})}>CONFIRM</button><button onClick={()=>action.mutate({id:m.id,path:'respond/DECLINE'})}>DECLINE</button></>}</div></div>)}</div>}</SABentoCard>}
const label=(value:string)=>value.toLowerCase().split('_').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ');
