package com.saproduction.command.dashboard;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
@Service
public class DashboardService {
  public record Team(long employees,long present,long late,long absent,long leave,long incomplete){}
  public record Today(UUID id,String type,String title,Instant startsAt,Instant endsAt){}
  public record Production(UUID id,String title,String status,int progressPercent,LocalDate eventDate){}
  public record Workload(UUID employeeId,String employeeName,long active,long overdue){}
  public record Payroll(UUID id,int year,int month,String status,long totalMinor,long paidMinor,long pendingMinor){}
  public record Attention(String code,String title,String detail,String tone,String href){}
  public record View(Team team,List<Today> today,List<Production> productions,List<Workload> workload,Payroll payroll,List<Attention> attention,boolean communicationsAvailable){}
  private final JdbcTemplate jdbc;private final ZoneId zone;
  public DashboardService(JdbcTemplate jdbc,@Value("${app.time-zone:Asia/Kolkata}") String zone){this.jdbc=jdbc;this.zone=ZoneId.of(zone);}
  @Transactional(readOnly=true) public View dashboard(){LocalDate today=LocalDate.now(zone);Instant start=today.atStartOfDay(zone).toInstant(),end=today.plusDays(1).atStartOfDay(zone).toInstant();long employees=count("select count(*) from employees where status<>'INACTIVE'");Map<String,Long> states=new HashMap<>();jdbc.query("select status,count(*) from attendance_records where attendance_date=? group by status",r->{states.put(r.getString(1),r.getLong(2));},today);long recorded=states.values().stream().mapToLong(Long::longValue).sum();Team team=new Team(employees,states.getOrDefault("PRESENT",0L),states.getOrDefault("LATE",0L),states.getOrDefault("ABSENT",0L),states.getOrDefault("LEAVE",0L),Math.max(0,employees-recorded));var schedule=jdbc.query("select id,type,title,starts_at,ends_at from calendar_events where status='SCHEDULED' and starts_at<? and ends_at>? order by starts_at",(r,n)->new Today(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getTimestamp(4).toInstant(),r.getTimestamp(5).toInstant()),Timestamp.from(end),Timestamp.from(start));var productions=jdbc.query("select id,title,status,progress_percent,event_date from productions where status not in ('DELIVERED','CANCELLED') order by case priority when 'URGENT' then 0 when 'HIGH' then 1 else 2 end,event_date limit 4",(r,n)->new Production(r.getObject(1,UUID.class),r.getString(2),r.getString(3),r.getInt(4),r.getObject(5,LocalDate.class)));var workload=jdbc.query("select e.id,e.display_name,count(t.id) filter(where t.status not in ('DONE','CANCELLED')),count(t.id) filter(where t.due_at<now() and t.status not in ('DONE','CANCELLED')) from employees e left join tasks t on t.assigned_employee_id=e.id where e.status<>'INACTIVE' group by e.id,e.display_name order by count(t.id) filter(where t.status not in ('DONE','CANCELLED')) desc,e.display_name limit 6",(r,n)->new Workload(r.getObject(1,UUID.class),r.getString(2),r.getLong(3),r.getLong(4)));Payroll payroll=jdbc.query("select p.id,p.year,p.month,p.status,coalesce(sum(i.net_salary_minor),0),coalesce(sum(i.net_salary_minor) filter(where i.payment_status='PAID'),0) from payroll_periods p left join payroll_items i on i.payroll_period_id=p.id group by p.id order by p.year desc,p.month desc limit 1",r->r.next()?new Payroll(r.getObject(1,UUID.class),r.getInt(2),r.getInt(3),r.getString(4),r.getLong(5),r.getLong(6),r.getLong(5)-r.getLong(6)):null);List<Attention> attention=attention(today);return new View(team,schedule,productions,workload,payroll,attention,false);}
  public List<Attention> attention(LocalDate today){List<Attention> result=new ArrayList<>();long overdue=count("select count(*) from tasks where due_at<now() and status not in ('DONE','CANCELLED')");if(overdue>0)result.add(new Attention("OVERDUE_TASKS","Overdue work",overdue+" task"+(overdue==1?"":"s")+" need attention","danger","/work"));long incomplete=count("select count(*) from employees e where e.status<>'INACTIVE' and not exists(select 1 from attendance_records a where a.employee_id=e.id and a.attendance_date=?)",today);if(incomplete>0)result.add(new Attention("ATTENDANCE_INCOMPLETE","Attendance incomplete",incomplete+" employee"+(incomplete==1?"":"s")+" not recorded","warning","/attendance"));long high=count("select count(*) from productions where priority in ('HIGH','URGENT') and status not in ('DELIVERED','CANCELLED') and event_date<=?",today.plusDays(7));if(high>0)result.add(new Attention("HIGH_PRIORITY_PRODUCTION","Production approaching",high+" high-priority production"+(high==1?"":"s")+" within seven days","warning","/productions"));String payroll=jdbc.query("select status from payroll_periods order by year desc,month desc limit 1",r->r.next()?r.getString(1):null);if(payroll==null||Set.of("DRAFT","CALCULATED","APPROVED").contains(payroll))result.add(new Attention("PAYROLL_ACTION","Payroll awaits action",payroll==null?"Current payroll has not been calculated":payroll.toLowerCase().replace('_',' '),"neutral","/payroll"));return result;}
  private long count(String sql,Object... args){return Objects.requireNonNull(jdbc.queryForObject(sql,Long.class,args));}
}
