import { useRef, useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { navigatorApi } from "../src/api/navigatorApi";
import { ApiError, type ApiErrorCode } from "../src/api/client";
import { credentials } from "../src/storage/credentials";
import { useEmployee } from "../src/state/employeeContext";
import { ActionButton, BrandMark, Card, Page, styles } from "../src/components/ui";
import { colors } from "../src/theme/tokens";
const pairingMessage=(code:ApiErrorCode)=>({INVALID_CODE:"That code isn't valid. Check all six digits and try again.",EXPIRED_CODE:"That code has expired. Ask your administrator for a new one.",ALREADY_USED:"That code has already been used. Ask for a new pairing code.",RATE_LIMITED:"Too many attempts. Wait a moment before trying again.",NETWORK_UNAVAILABLE:"You're offline. Connect to the internet and try again.",SERVER_UNAVAILABLE:"SA Productions is temporarily unavailable.",TIMEOUT:"The connection took too long. Please try again.",AUTH_REQUIRED:"A new pairing code is required.",DEVICE_REVOKED:"This device needs a new pairing code.",INVALID_REQUEST:"The code could not be accepted.",UNKNOWN:"The phone could not be connected."}[code]);
export default function Pair(){const [code,setCode]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");const input=useRef<TextInput>(null),{paired}=useEmployee();async function submit(){if(code.length!==6||busy)return;setBusy(true);setError("");try{const result=await navigatorApi.pair(code,`${Platform.OS} employee phone`);await credentials.set(result.deviceToken);await paired();router.replace("/(employee)");}catch(cause){setError(pairingMessage(cause instanceof ApiError?cause.code:"UNKNOWN"));}finally{setBusy(false)}}return <KeyboardAvoidingView style={{flex:1,backgroundColor:colors.background}} behavior={Platform.OS==="ios"?"padding":undefined}><Page><View style={{paddingTop:38,gap:28}}><BrandMark/><View><Text style={styles.greeting}>Connect to{`\n`}SA Productions</Text><Text style={[styles.body,{marginTop:10}]}>Enter the 6-digit code provided by your administrator.</Text></View><Card emphasis><Pressable accessibilityRole="button" accessibilityLabel="Pairing code" onPress={()=>input.current?.focus()} style={{flexDirection:"row",justifyContent:"space-between"}}>{Array.from({length:6},(_,i)=><View key={i} style={{width:42,height:54,borderRadius:13,borderWidth:1,borderColor:i===code.length?colors.text:colors.borderStrong,backgroundColor:colors.surfaceSoft,alignItems:"center",justifyContent:"center"}}><Text style={{fontSize:22,fontWeight:"700",color:colors.text}}>{code[i]??""}</Text></View>)}</Pressable><TextInput ref={input} value={code} onChangeText={value=>setCode(value.replace(/\D/g,"").slice(0,6))} keyboardType="number-pad" textContentType="oneTimeCode" caretHidden style={{position:"absolute",opacity:0,width:1,height:1}} onSubmitEditing={submit}/>{error?<Text accessibilityRole="alert" style={{color:colors.danger,lineHeight:20}}>{error}</Text>:null}<ActionButton busy={busy} disabled={code.length!==6} onPress={submit}>{busy?"Connecting device…":"Connect device"}</ActionButton></Card><Text style={[styles.meta,{textAlign:"center"}]}>Your device credential is encrypted on this phone.</Text></View></Page></KeyboardAvoidingView>}
