package com.saproduction.command.payroll;
import com.saproduction.command.audit.AuditService;
import com.saproduction.command.auth.UserRepository;
import com.saproduction.command.employee.*;
import com.saproduction.command.shared.ApiException;
import jakarta.validation.constraints.*;
import java.time.*;
import java.util.*;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class PayrollService {
  public record AdjustmentInput(@NotNull UUID itemId,@NotNull PayrollAdjustment.Type type,long amountMinor,@NotBlank @Size(max=500) String reason){}
  public record AdjustmentView(UUID id,PayrollAdjustment.Type type,long amountMinor,String reason,Instant createdAt){}
  public record ItemView(UUID id,UUID employeeId,String employeeName,String salaryCurrency,long baseSalaryMinor,long attendanceDeductionMinor,long overtimeMinor,long bonusMinor,long advanceDeductionMinor,long manualAdjustmentMinor,long netSalaryMinor,PayrollItem.PaymentStatus paymentStatus,Instant paidAt,List<AdjustmentView> adjustments){}
  public record View(UUID id,int year,int month,PayrollPeriod.Status status,String policy,long totalMinor,long paidMinor,long pendingMinor,List<ItemView> items,Instant calculatedAt,Instant approvedAt,Instant paidAt,Instant lockedAt){}
  private final PayrollPeriodRepository periods;private final PayrollItemRepository items;private final PayrollAdjustmentRepository adjustments;private final EmployeeRepository employees;private final PayrollCalculationPolicy policy;private final UserRepository users;private final AuditService audit;
  public PayrollService(PayrollPeriodRepository periods,PayrollItemRepository items,PayrollAdjustmentRepository adjustments,EmployeeRepository employees,PayrollCalculationPolicy policy,UserRepository users,AuditService audit){this.periods=periods;this.items=items;this.adjustments=adjustments;this.employees=employees;this.policy=policy;this.users=users;this.audit=audit;}
  @Transactional(readOnly=true) public List<View> list(){return periods.findAllByOrderByYearDescMonthDesc().stream().map(this::view).toList();}
  @Transactional(readOnly=true) public View get(UUID id){return view(period(id));}
  @Transactional public View calculate(int year,int month){YearMonth ym;try{ym=YearMonth.of(year,month);}catch(Exception e){throw ApiException.badRequest("INVALID_PAYROLL_PERIOD","Payroll month is invalid.");}PayrollPeriod p=periods.findByYearAndMonth(year,month).orElseGet(()->{PayrollPeriod x=new PayrollPeriod();x.year=year;x.month=month;return periods.saveAndFlush(x);});if(p.status!=PayrollPeriod.Status.DRAFT&&p.status!=PayrollPeriod.Status.CALCULATED)throw state(p);boolean recalculation=p.status==PayrollPeriod.Status.CALCULATED;for(Employee employee:employees.findAllByStatusNotOrderByDisplayName(Employee.Status.INACTIVE)){PayrollItem item=items.findByPayrollPeriodIdAndEmployeeId(p.id,employee.id).orElseGet(PayrollItem::new);item.payrollPeriodId=p.id;item.employeeId=employee.id;item.employeeNameSnapshot=employee.displayName;item.salaryCurrency=employee.salaryCurrency;item.baseSalaryMinor=employee.baseSalaryMinor;item.attendanceDeductionMinor=policy.attendanceDeduction(employee,ym);if(item.paymentStatus==null)item.paymentStatus=PayrollItem.PaymentStatus.PENDING;items.saveAndFlush(item);recompute(item);}p.status=PayrollPeriod.Status.CALCULATED;p.calculatedAt=Instant.now();periods.save(p);var result=view(p);audit.record("PAYROLL",recalculation?"PAYROLL_RECALCULATED":"PAYROLL_CALCULATED",p.id.toString(),null,result);return result;}
  @Transactional public View adjust(UUID periodId,AdjustmentInput in){PayrollPeriod p=period(periodId);require(p,PayrollPeriod.Status.CALCULATED);PayrollItem item=items.findById(in.itemId()).filter(x->x.payrollPeriodId.equals(periodId)).orElseThrow(()->ApiException.notFound("PAYROLL_ITEM_NOT_FOUND","Payroll item was not found."));if(in.amountMinor()==0)throw ApiException.badRequest("INVALID_ADJUSTMENT","Adjustment amount cannot be zero.");if(EnumSet.of(PayrollAdjustment.Type.BONUS,PayrollAdjustment.Type.DEDUCTION,PayrollAdjustment.Type.OVERTIME,PayrollAdjustment.Type.ADVANCE).contains(in.type())&&in.amountMinor()<0)throw ApiException.badRequest("INVALID_ADJUSTMENT","This adjustment type requires a positive amount.");PayrollAdjustment a=new PayrollAdjustment();a.payrollItemId=item.id;a.type=in.type();a.amountMinor=in.amountMinor();a.reason=in.reason().trim();a.createdBy=currentUser();adjustments.save(a);recompute(item);audit.record("PAYROLL","PAYROLL_ADJUSTMENT_ADDED",periodId.toString(),null,Map.of("itemId",item.id,"type",a.type,"amountMinor",a.amountMinor,"reason",a.reason));return view(p);}
  @Transactional public View approve(UUID id){PayrollPeriod p=period(id);require(p,PayrollPeriod.Status.CALCULATED);p.status=PayrollPeriod.Status.APPROVED;p.approvedAt=Instant.now();periods.save(p);var result=view(p);audit.record("PAYROLL","PAYROLL_APPROVED",id.toString(),null,result);return result;}
  @Transactional public View markPaid(UUID id,UUID itemId){PayrollPeriod p=period(id);require(p,PayrollPeriod.Status.APPROVED);PayrollItem item=items.findById(itemId).filter(x->x.payrollPeriodId.equals(id)).orElseThrow(()->ApiException.notFound("PAYROLL_ITEM_NOT_FOUND","Payroll item was not found."));item.paymentStatus=PayrollItem.PaymentStatus.PAID;item.paidAt=Instant.now();items.save(item);audit.record("PAYROLL","PAYROLL_ITEM_PAID",id.toString(),null,Map.of("itemId",itemId));if(items.countByPayrollPeriodIdAndPaymentStatus(id,PayrollItem.PaymentStatus.PENDING)==0){p.status=PayrollPeriod.Status.PAID;p.paidAt=Instant.now();periods.save(p);}return view(p);}
  @Transactional public View markAllPaid(UUID id){PayrollPeriod p=period(id);require(p,PayrollPeriod.Status.APPROVED);for(PayrollItem item:items.findAllByPayrollPeriodIdOrderByEmployeeNameSnapshot(id)){item.paymentStatus=PayrollItem.PaymentStatus.PAID;item.paidAt=Instant.now();items.save(item);}p.status=PayrollPeriod.Status.PAID;p.paidAt=Instant.now();periods.save(p);audit.record("PAYROLL","PAYROLL_ALL_PAID",id.toString(),null,view(p));return view(p);}
  @Transactional public View lock(UUID id){PayrollPeriod p=period(id);require(p,PayrollPeriod.Status.PAID);p.status=PayrollPeriod.Status.LOCKED;p.lockedAt=Instant.now();periods.save(p);var result=view(p);audit.record("PAYROLL","PAYROLL_LOCKED",id.toString(),null,result);return result;}
  private void recompute(PayrollItem item){long bonus=0,overtime=0,advance=0,manual=0;for(PayrollAdjustment a:adjustments.findAllByPayrollItemIdOrderByCreatedAt(item.id)){switch(a.type){case BONUS->bonus=Math.addExact(bonus,a.amountMinor);case OVERTIME->overtime=Math.addExact(overtime,a.amountMinor);case ADVANCE->advance=Math.addExact(advance,a.amountMinor);case DEDUCTION->manual=Math.subtractExact(manual,a.amountMinor);case CORRECTION,OTHER->manual=Math.addExact(manual,a.amountMinor);}}item.bonusMinor=bonus;item.overtimeMinor=overtime;item.advanceDeductionMinor=advance;item.manualAdjustmentMinor=manual;item.netSalaryMinor=Math.addExact(Math.subtractExact(item.baseSalaryMinor,item.attendanceDeductionMinor),Math.addExact(Math.addExact(overtime,bonus),Math.subtractExact(manual,advance)));items.save(item);}
  private View view(PayrollPeriod p){var views=items.findAllByPayrollPeriodIdOrderByEmployeeNameSnapshot(p.id).stream().map(this::itemView).toList();long total=views.stream().mapToLong(ItemView::netSalaryMinor).sum();long paid=views.stream().filter(i->i.paymentStatus()==PayrollItem.PaymentStatus.PAID).mapToLong(ItemView::netSalaryMinor).sum();return new View(p.id,p.year,p.month,p.status,policy.name(),total,paid,total-paid,views,p.calculatedAt,p.approvedAt,p.paidAt,p.lockedAt);}
  private ItemView itemView(PayrollItem i){return new ItemView(i.id,i.employeeId,i.employeeNameSnapshot,i.salaryCurrency,i.baseSalaryMinor,i.attendanceDeductionMinor,i.overtimeMinor,i.bonusMinor,i.advanceDeductionMinor,i.manualAdjustmentMinor,i.netSalaryMinor,i.paymentStatus,i.paidAt,adjustments.findAllByPayrollItemIdOrderByCreatedAt(i.id).stream().map(a->new AdjustmentView(a.id,a.type,a.amountMinor,a.reason,a.createdAt)).toList());}
  private void require(PayrollPeriod p,PayrollPeriod.Status expected){if(p.status!=expected)throw state(p);}
  private ApiException state(PayrollPeriod p){return ApiException.conflict(p.status==PayrollPeriod.Status.LOCKED?"PAYROLL_LOCKED":"INVALID_PAYROLL_STATE","Payroll action is not allowed while the period is "+p.status+".");}
  private PayrollPeriod period(UUID id){return periods.findById(id).orElseThrow(()->ApiException.notFound("PAYROLL_NOT_FOUND","Payroll period was not found."));}
  private UUID currentUser(){var a=SecurityContextHolder.getContext().getAuthentication();return a==null?null:users.findByEmailIgnoreCase(a.getName()).map(u->u.id).orElse(null);}
}
