import type { PropsWithChildren, ReactNode } from "react";
import { ActivityIndicator, Animated, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View, type PressableProps } from "react-native";
import { colors, radius, space } from "../theme/tokens";
import type { ConnectionState } from "../network/connection";

export function Page({children,scroll=true,refreshControl}:{children:ReactNode;scroll?:boolean;refreshControl?:ReactNode}){
  const content=<View style={styles.page}>{children}<View style={{height:96}}/></View>;
  return <SafeAreaView style={styles.safe}>{scroll?<ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false} refreshControl={refreshControl as never}>{content}</ScrollView>:content}</SafeAreaView>;
}
export function BrandMark({compact=false}:{compact?:boolean}){return <View style={styles.brandRow}><View style={styles.mark}><Text style={styles.markText}>S</Text></View><View><Text style={styles.company}>SA PRODUCTIONS</Text>{!compact&&<Text style={styles.brand}>Employee</Text>}</View></View>}
export function SectionLabel({children}:PropsWithChildren){return <Text style={styles.eyebrow}>{children}</Text>}
export function Card({children,emphasis=false}:PropsWithChildren<{emphasis?:boolean}>){return <View style={[styles.card,emphasis&&styles.cardEmphasis]}>{children}</View>}
export function Badge({label,tone="neutral"}:{label:string;tone?:"neutral"|"success"|"warning"|"danger"|"info"}){return <View style={[styles.badge,{backgroundColor:{neutral:colors.surfaceSoft,success:"rgba(79,149,106,.17)",warning:"rgba(197,138,52,.17)",danger:"rgba(201,83,75,.17)",info:"rgba(95,127,164,.18)"}[tone]}]}><Text style={[styles.badgeText,{color:{neutral:colors.textSecondary,success:"#82C49A",warning:"#E0B469",danger:"#E27C74",info:"#8FAFD2"}[tone]}]}>{label}</Text></View>}
export function ActionButton({children,variant="primary",busy,...props}:PropsWithChildren<PressableProps&{variant?:"primary"|"danger"|"secondary";busy?:boolean}>){return <Pressable accessibilityRole="button" {...props} disabled={props.disabled||busy} style={({pressed})=>[styles.button,variant==="danger"&&styles.buttonDanger,variant==="secondary"&&styles.buttonSecondary,pressed&&styles.pressed,(props.disabled||busy)&&styles.disabled]}>{busy?<ActivityIndicator color={colors.text}/>:<Text style={styles.buttonText}>{children}</Text>}</Pressable>}
export function Row({title,detail,action}:{title:string;detail?:string;action?:ReactNode}){return <View style={styles.row}><View style={{flex:1,gap:3}}><Text style={styles.rowTitle}>{title}</Text>{detail&&<Text style={styles.meta}>{detail}</Text>}</View>{action}</View>}
export function EmptyState({title,body}:{title:string;body:string}){return <View style={styles.empty}><Text style={styles.emptyGlyph}>○</Text><Text style={styles.rowTitle}>{title}</Text><Text style={styles.body}>{body}</Text></View>}
export function ConnectionBanner({state}:{state:ConnectionState}){if(state==="ONLINE")return null;const text={CONNECTING:"Connecting to SA Productions…",DEGRADED:"Connection is unstable · recent information remains available",OFFLINE:"You're offline · updates will sync automatically",AUTH_REQUIRED:"This device needs to be connected again",SERVICE_UNAVAILABLE:"SA Productions is temporarily unavailable"}[state];return <View style={styles.banner}><Text style={styles.bannerText}>{text}</Text></View>}
export function Skeleton(){return <View style={styles.skeleton}><View style={[styles.skeletonLine,{width:"42%"}]}/><View style={[styles.skeletonLine,{width:"78%"}]}/><View style={[styles.skeletonLine,{width:"62%"}]}/></View>}
export const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},scroll:{flexGrow:1},page:{paddingHorizontal:18,paddingTop:14,gap:18},brandRow:{flexDirection:"row",alignItems:"center",gap:12},mark:{width:42,height:42,borderRadius:14,backgroundColor:colors.text,alignItems:"center",justifyContent:"center"},markText:{fontSize:22,fontWeight:"900",fontStyle:"italic",color:colors.background},company:{fontSize:10,letterSpacing:1.8,fontWeight:"800",color:colors.textTertiary},brand:{fontSize:18,fontWeight:"700",color:colors.text,marginTop:2},greeting:{fontSize:30,lineHeight:36,fontWeight:"700",color:colors.text},date:{fontSize:14,color:colors.textTertiary,marginTop:5},eyebrow:{fontSize:10,letterSpacing:1.7,fontWeight:"800",color:colors.textTertiary},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.card,padding:20,gap:13},cardEmphasis:{backgroundColor:colors.surfaceRaised,borderColor:colors.borderStrong},title:{fontSize:23,lineHeight:29,fontWeight:"700",color:colors.text},body:{fontSize:15,lineHeight:22,color:colors.textSecondary},meta:{fontSize:12,lineHeight:17,color:colors.textTertiary},badge:{alignSelf:"flex-start",borderRadius:999,paddingVertical:6,paddingHorizontal:10},badgeText:{fontSize:10,fontWeight:"800",letterSpacing:.7,textTransform:"uppercase"},button:{minHeight:54,borderRadius:radius.button,backgroundColor:colors.text,alignItems:"center",justifyContent:"center",paddingHorizontal:18},buttonDanger:{backgroundColor:colors.danger},buttonSecondary:{backgroundColor:colors.surfaceSoft,borderWidth:1,borderColor:colors.border},buttonText:{fontSize:15,fontWeight:"800",color:colors.background},pressed:{transform:[{scale:.985}],opacity:.88},disabled:{opacity:.45},row:{flexDirection:"row",alignItems:"center",gap:12,paddingVertical:6},rowTitle:{fontSize:15,fontWeight:"700",color:colors.text},empty:{alignItems:"center",paddingVertical:22,gap:7},emptyGlyph:{fontSize:28,color:colors.textTertiary},banner:{borderRadius:radius.sm,backgroundColor:"rgba(197,138,52,.14)",borderWidth:1,borderColor:"rgba(197,138,52,.25)",paddingVertical:10,paddingHorizontal:13},bannerText:{fontSize:12,fontWeight:"600",color:"#E0B469"},skeleton:{gap:10},skeletonLine:{height:13,borderRadius:7,backgroundColor:colors.surfaceSoft}});
