import {useQuery} from '@tanstack/react-query';
import {ArrowUpRight,CalendarClock,MessageCircle,Users} from 'lucide-react';
import {WorkspaceHeader} from '../../components/layout/AppShell';
import {CardHeader,SABentoCard,SABentoGrid,SAProgress,SARadialMetric,StatusBadge} from '../../components/ui/sa';
import {api} from '../../lib/api';
import type {AttendanceDay,Employee} from '../../types/domain';
import {commandMock} from './mockData';
const today=()=>new Date().toISOString().slice(0,10);
export function CommandPage(){const employees=useQuery({queryKey:['employees'],queryFn:()=>api<Employee[]>('/employees')});const attendance=useQuery({queryKey:['attendance',today()],queryFn:()=>api<AttendanceDay>(`/attendance?date=${today()}`)});const now=new Date();const total=employees.data?.filter(e=>e.status!=='INACTIVE').length??0;const present=(attendance.data?.summary.PRESENT??0)+(attendance.data?.summary.LATE??0);const attendancePct=total?Math.round(present/total*100):0;return <><WorkspaceHeader title={`${greeting()}, Owner.`} subtitle="Here’s the operating picture for today."/><SABentoGrid className="command-grid">
  <SABentoCard className="time-card"><span className="eyebrow">Local time</span><strong className="hero-time">{now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</strong><p>{now.toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'})}</p><div className="time-marker"><CalendarClock size={15}/>Next review at 11:30</div></SABentoCard>
  <SABentoCard className="today-card"><CardHeader eyebrow="Schedule preview" title="Today" action={<ArrowUpRight size={16}/>}/><div className="timeline">{commandMock.today.map(item=><div key={item.time}><time>{item.time}</time><span/><div><strong>{item.title}</strong><small>{item.kind}</small></div></div>)}</div></SABentoCard>
  <SABentoCard className="team-card"><CardHeader eyebrow="Live Phase 1 data" title="Team status"/><div className="team-content"><SARadialMetric value={attendancePct} label={`${present} of ${total} accounted`}/><div className="team-breakdown"><div><span>Present</span><strong>{attendance.data?.summary.PRESENT??'—'}</strong></div><div><span>Late</span><strong>{attendance.data?.summary.LATE??'—'}</strong></div><div><span>Absent</span><strong>{attendance.data?.summary.ABSENT??'—'}</strong></div><div><span>Leave</span><strong>{attendance.data?.summary.LEAVE??'—'}</strong></div></div></div></SABentoCard>
  <SABentoCard className="attendance-card"><CardHeader eyebrow="Attendance" title="Today"/><strong className="compact-metric">{present}</strong><span className="muted">present or checked in</span><div className="mini-footer"><Users size={15}/>{total} active people</div></SABentoCard>
  <SABentoCard className="comms-card"><CardHeader eyebrow="Later-phase preview" title="Communications"/><div className="donut-mini"><MessageCircle size={19}/><strong>{commandMock.communications.delivered}</strong><span>delivered</span></div><div className="inline-stats"><span>{commandMock.communications.waiting} waiting</span><span className="danger-text">{commandMock.communications.failed} failed</span></div></SABentoCard>
  <SABentoCard className="productions-card"><CardHeader eyebrow="Later-phase preview" title="Active productions" action={<StatusBadge tone="neutral">Typed mock</StatusBadge>}/><div className="production-list">{commandMock.productions.slice(0,2).map(p=><div key={p.name}><div><strong>{p.name}</strong><span>{p.stage} · {p.date}</span></div><div><b>{p.progress}%</b><SAProgress value={p.progress}/></div></div>)}</div></SABentoCard>
  <SABentoCard className="workload-card"><CardHeader eyebrow="Later-phase preview" title="Workload"/><div className="workload-ring"><SARadialMetric value={commandMock.workload.capacity} label="team capacity"/></div><p><strong>{commandMock.workload.overloaded}</strong> crew members need review</p></SABentoCard>
  <SABentoCard className="payroll-card"><CardHeader eyebrow="Later-phase preview" title="Payroll"/><strong className="compact-metric">{money(commandMock.payroll.estimateMinor)}</strong><span className="muted">{commandMock.payroll.period} estimate</span><StatusBadge tone="neutral">{commandMock.payroll.state}</StatusBadge></SABentoCard>
  <SABentoCard className="attention-card"><CardHeader eyebrow="Owner queue" title="Needs attention"/><div className="attention-list">{commandMock.attention.map(item=><div key={item.title}><StatusBadge tone={item.tone}>{item.tone==='neutral'?'Waiting':'Review'}</StatusBadge><div><strong>{item.title}</strong><span>{item.detail}</span></div><ArrowUpRight size={15}/></div>)}</div></SABentoCard>
  </SABentoGrid></>}
function greeting(){const h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':'Good evening'}
function money(minor:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(minor/100)}
