import * as SQLite from "expo-sqlite";
export type QueuedPoint={id:number;sessionId:string;sequenceNo:number;latitude:number;longitude:number;accuracyMeters:number|null;recordedAt:string;attemptCount:number};
let database:Promise<SQLite.SQLiteDatabase>|undefined;
async function db(){database??=SQLite.openDatabaseAsync("navigator-queue.db");const value=await database;await value.execAsync(`CREATE TABLE IF NOT EXISTS queued_location_points(id INTEGER PRIMARY KEY AUTOINCREMENT,session_id TEXT NOT NULL,sequence_no INTEGER NOT NULL,latitude REAL NOT NULL,longitude REAL NOT NULL,accuracy_meters REAL,recorded_at TEXT NOT NULL,attempt_count INTEGER NOT NULL DEFAULT 0,next_attempt_at TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(session_id,sequence_no));CREATE INDEX IF NOT EXISTS idx_queue_ready ON queued_location_points(next_attempt_at,id);CREATE TABLE IF NOT EXISTS pending_duty_end(session_id TEXT PRIMARY KEY,ended_at TEXT NOT NULL);`);return value;}
export async function enqueue(point:Omit<QueuedPoint,"id"|"attemptCount">){if(!Number.isFinite(point.latitude)||!Number.isFinite(point.longitude)||point.latitude< -90||point.latitude>90||point.longitude< -180||point.longitude>180)return;const value=await db(),now=new Date().toISOString();await value.runAsync("INSERT OR IGNORE INTO queued_location_points(session_id,sequence_no,latitude,longitude,accuracy_meters,recorded_at,next_attempt_at,created_at) VALUES (?,?,?,?,?,?,?,?)",point.sessionId,point.sequenceNo,point.latitude,point.longitude,point.accuracyMeters,point.recordedAt,now,now);await value.runAsync("DELETE FROM queued_location_points WHERE id IN (SELECT id FROM queued_location_points WHERE created_at < datetime('now','-1 day') ORDER BY id LIMIT 5000)");await value.runAsync("DELETE FROM queued_location_points WHERE id NOT IN (SELECT id FROM queued_location_points ORDER BY id DESC LIMIT 5000)");}
export async function ready(){return (await db()).getAllAsync<QueuedPoint>("SELECT id,session_id sessionId,sequence_no sequenceNo,latitude,longitude,accuracy_meters accuracyMeters,recorded_at recordedAt,attempt_count attemptCount FROM queued_location_points WHERE next_attempt_at <= ? ORDER BY id LIMIT 25",new Date().toISOString());}
export async function acknowledge(ids:number[]){if(!ids.length)return;const value=await db();await value.runAsync(`DELETE FROM queued_location_points WHERE id IN (${ids.map(()=>"?").join(",")})`,...ids);}
export async function defer(ids:number[],attempt:number){if(!ids.length)return;const delays=[5,15,45,120,300],seconds=delays[Math.min(attempt,delays.length-1)]+Math.floor(Math.random()*4);const value=await db();await value.runAsync(`UPDATE queued_location_points SET attempt_count=attempt_count+1,next_attempt_at=? WHERE id IN (${ids.map(()=>"?").join(",")})`,new Date(Date.now()+seconds*1000).toISOString(),...ids);}
export async function pendingDutyEnd(){return (await db()).getFirstAsync<{sessionId:string;endedAt:string}>("SELECT session_id sessionId,ended_at endedAt FROM pending_duty_end LIMIT 1");}
export async function savePendingDutyEnd(sessionId:string,endedAt:string){await (await db()).runAsync("INSERT OR REPLACE INTO pending_duty_end(session_id,ended_at) VALUES (?,?)",sessionId,endedAt);}
export async function clearPendingDutyEnd(sessionId:string){await (await db()).runAsync("DELETE FROM pending_duty_end WHERE session_id=?",sessionId);}
export async function pendingPointCount(){const row=await (await db()).getFirstAsync<{count:number}>("SELECT COUNT(*) count FROM queued_location_points");return row?.count??0;}
