import { CONSENT_VERSION } from "../config";
import { acknowledge,clearPendingDutyEnd,defer,pendingDutyEnd,ready } from "../queue/locationQueue";
import { apiRequest } from "./client";
import { ApiError } from "./client";
export type MobileMessage={id:string;title:string;body:string;sentAt:string;read:boolean};
export type MobileHome={displayName:string;dutyActive:boolean;sessionId?:string;startedAt?:string;serverLastLocationAt?:string;productionRef?:string;productionTitle?:string;locationName?:string;startsAt?:string;endsAt?:string;messages:MobileMessage[]};
export const navigatorApi={pair:(code:string,label:string)=>apiRequest<{deviceId:string;employeeRef:string;deviceToken:string}>("/api/v1/mobile/pairings/redeem",{method:"POST",body:JSON.stringify({code,platform:"ANDROID",deviceLabel:label})},false),home:()=>apiRequest<MobileHome>("/api/v1/mobile/home"),start:()=>apiRequest<{sessionId:string;startedAt:string}>("/api/v1/mobile/duty/start",{method:"POST",body:JSON.stringify({consentVersion:CONSENT_VERSION})}),end:(id:string,endedAt:string)=>apiRequest<void>("/api/v1/mobile/duty/end",{method:"POST",body:JSON.stringify({sessionId:id,endedAt})}),state:()=>apiRequest<{deviceId:string;employeeRef:string;revoked:boolean}>("/api/v1/mobile/state")};
export async function flushQueue(){const points=await ready();if(!points.length)return 0;const batch=points.filter(point=>point.sessionId===points[0].sessionId);try{const result=await apiRequest<{acknowledgedSequenceNumbers:number[]}>("/api/v1/mobile/locations/batch",{method:"POST",body:JSON.stringify({sessionId:batch[0].sessionId,points:batch.map(p=>({sequenceNo:p.sequenceNo,latitude:p.latitude,longitude:p.longitude,accuracyMeters:p.accuracyMeters,recordedAt:p.recordedAt}))})});const accepted=new Set(result.acknowledgedSequenceNumbers);await acknowledge(batch.filter(p=>accepted.has(p.sequenceNo)).map(p=>p.id));return accepted.size;}catch(error){if(error instanceof ApiError&&error.status&&error.status>=400&&error.status<500&&error.status!==429)await acknowledge(batch.map(p=>p.id));else await defer(batch.map(p=>p.id),Math.max(...batch.map(p=>p.attemptCount)));throw error;}}
export async function flushPendingDutyEnd(){const pending=await pendingDutyEnd();if(!pending)return false;await flushQueue();await navigatorApi.end(pending.sessionId,pending.endedAt);await clearPendingDutyEnd(pending.sessionId);return true;}
